### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by Gigahawk** [rajveermalviya/go-webgpu#269]
Seems to install fine on linux (using WSL so it won't actually find an adapter)
```
$ go run github.com/rajveermalviya/go-webgpu-examples/compute@latest
go: downloading github.com/rajveermalviya/go-webgpu-examples v0.0.0-20230730112648-c29c7b8006e5
go: downloading github.com/rajveermalviya/go-webgpu/wgpu v0.17.1
panic: failed to request adapter

goroutine 1 [running]:
main.main()
        /home/jasper/go/pkg/mod/github.com/rajveermalviya/go-webgpu-examples@v0.0.0-20230730112648-c29c7b8006e5/compute/main.go:49 +0xc49
exit status 2

$ go version
go version go1.22.3 linux/amd64
```

But when I try to run it on Windows I get:
```
PS C:\> go run github.com/rajveermalviya/go-webgpu-examples/compute@latest
# github.com/rajveermalviya/go-webgpu/wgpu
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\defaults.go:3:22: undefined: Limits
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\device_ext.go:9:10: undefined: Device
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\device_ext.go:9:71: undefined: Buffer
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\texture_ext.go:3:10: undefined: Texture
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\texture_ext.go:3:34: undefined: ImageCopyTexture
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:25:22: undefined: Color
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:26:22: undefined: Color
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:27:22: undefined: Color
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:28:22: undefined: Color
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:29:22: undefined: Color
go\pkg\mod\github.com\rajveermalviya\go-webgpu\wgpu@v0.17.1\wgpu_ext.go:29:22: too many errors
PS C:\> go version
go version go1.20.14 windows/amd64
```
Tried also with go1.23.0, same issue

**Comment by rcoreilly** [comment]
We have a maintained fork of this package that definitely works on windows: https://github.com/cogentcore/webgpu
